### ISSUE TITLE
Boostnote 0.8.18 doesn't work in Linux Mint 18.2

### ISSUE THREAD

**Issue by Osahar** [BoostIO/Boostnote#1237]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2438%20Funded-%2300A156.svg" />](https://issuehunt.io/r/BoostIo/Boostnote/issues/1237)

I was using version 0.8.14 on Linux Mint 18.2 and it was working perfect. Now I have updated boostnote to 0.8.18 and it doesn't open anymore. I get this error from terminal when trying to open the program:

module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/share/boostnote/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/usr/share/boostnote/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/usr/share/boostnote/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:300:26)

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $38.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($30.00)
- [<img src='https://avatars3.githubusercontent.com/u/13612118?v=4' alt='boostio' width=24 height=24> boostio](https://issuehunt.io/u/boostio) ($6.00)
- [<img src='https://avatars3.githubusercontent.com/u/8602615?v=4' alt='kazup01' width=24 height=24> kazup01](https://issuehunt.io/u/kazup01) ($2.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/BoostIo/Boostnote/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by FistfulOfStars** [comment]
Boostnote isn't shutting down correctly when closed. It needs to be killed.

Logging out or rebooting also fixes it.

Temporary workaround without logout/reboot:

    pidof Boostnote

Then

    kill 15 ***

Where *** is the smallest (probably last) listed PID from the pidof output.

It may throw an error "operation not permitted" but it does the job. Try relaunching Boostnote.

**Comment by Osahar** [comment]
Thank you, it was that.

Boostnote only opened the first time and then it did not open anymore.

I checked the processes through the terminal with the command "pidof boostnote" but I did not get an answer, so I thought the problem was different.

Now I have checked it in graphical mode with the system monitor application and there they were ... four of them having a dead-alive processes party :)

Sorry, I forgot to say I'm using the Cinnamon desktop. I tried it in Mate as well and it seems to work fine there.

---

Also, I want to thank Boostnote developers cause this is really such a great program!

**Comment by FistfulOfStars** [comment]
Yeah, it's "**B**oostnote" vs "**b**oostnote" - first Linux app I've experienced with a capital letter.

Interesting that it works on Mate. I wonder if 18.3 solves the issue.

**Comment by kazup01** [comment]
Hi @Osahar , how about state of the current version(v0.8.20)?

**Comment by FistfulOfStars** [comment]
Not the person you were asking, but I am in the same boat as they are.

v0.8.20 still doesn't terminate properly. Manual kill required still.

Linux Mint 18.2, Cinnamon 3.4.6

**Comment by amig** [comment]
I have same issue on Ubuntu Gnome 16.04.3. Boostnote 0.8.20-1

**Comment by Osahar** [comment]
Hi!

I have updated my operating system recently. I'm using Linux Mint 18.3 with the Cinnamon 3.6.7 desktop and it works fine for me now. It's not necessary to kill the process manually anymore.

To close the app you have to do it from an icon that shows up at the system tray (right clic with your mouse and chose "quit" from the dialog).

**Comment by amig** [comment]
I confirm what @Osahar wrote. Never noticed the tray icon in Gnome. Would be nice if the app is running and minimized, trying to relaunch it will just bring it's window to the front and not through a js error or maybe a setting that will determined if app is closed to tray or not.

**Comment by IssuehuntBot** [comment]
@charrismatic has started working. [Visit this issue on Issuehunt](https://issuehunt.io/repos/53266139/issues/1237)

**Comment by IssuehuntBot** [comment]
@kazup01 has cancelled funding for this issue.(Cancelled amount: $30.00) [See it on IssueHunt](https://issuehunt.io/repos/53266139/issues/1237)

**Comment by IssuehuntBot** [comment]
@issuehuntfest has funded $30.00 to this issue. [See it on IssueHunt](https://issuehunt.io/repos/53266139/issues/1237)

**Comment by IssuehuntBot** [comment]
@boostio has funded $1.00 to this issue.

---
- Submit pull request via [IssueHunt](https://issuehunt.io/repos/53266139/issues/1237) to receive this reward.
- Want to contribute? Chip in to this issue via [IssueHunt](https://issuehunt.io/repos/53266139/issues/1237).
- Checkout the [IssueHunt Issue Explorer](https://issuehunt.io/issues) to see more funded issues.
- Need help from developers? [Add your repository](https://issuehunt.io/users/13612118/repositories) on IssueHunt to raise funds.

**Comment by IssuehuntBot** [comment]
@boostio has funded $5.00 to this issue.

---
- Submit pull request via [IssueHunt](https://issuehunt.io/repos/53266139/issues/1237) to receive this reward.
- Want to contribute? Chip in to this issue via [IssueHunt](https://issuehunt.io/repos/53266139/issues/1237).
- Checkout the [IssueHunt Issue Explorer](https://issuehunt.io/issues) to see more funded issues.
- Need help from developers? [Add your repository](https://issuehunt.io/r/new) on IssueHunt to raise funds.

**Comment by IssueHuntBot** [comment]
@kazup01 has funded $2.00 to this issue.

---
- Submit pull request via [IssueHunt](https://issuehunt.io/repos/53266139/issues/1237) to receive this reward.
- Want to contribute? Chip in to this issue via [IssueHunt](https://issuehunt.io/repos/53266139/issues/1237).
- Checkout the [IssueHunt Issue Explorer](https://issuehunt.io/issues) to see more funded issues.
- Need help from developers? [Add your repository](https://issuehunt.io/r/new) on IssueHunt to raise funds.
